# [[file:../../kafka.org::73f1cba407ecf2feadd9f992ef63e8ca][73f1cba407ecf2feadd9f992ef63e8ca]]
---
version: '2'
services:
  zookeeper:
    container_name: zk_b2c3160f4fde3c178e18ad53aa40796d_1
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    container_name: kf_9982492f916ca04941d7ca5d40c9ed0f_1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  book_registry:
    container_name: br_350066aa7594c13f6a13c7fa2f0bd0fa_1
    build: ./registry
    image: book/registry
    depends_on:
      - kafka
    ports:
      - 8080:8080
    command: >-
      /app/wait-for-it.sh kafka:29092 -- bash -c "java -jar /app/target/registry-*.jar"
...
# 73f1cba407ecf2feadd9f992ef63e8ca ends here
